export const USER_LOGIN_START = 'USER_LOGIN_START';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_CANCEL = 'USER_LOGIN_CANCEL';
export const USER_LOGOUT_START = 'USER_LOGOUT_START';
export const USER_LOGOUT_FAIL = 'USER_LOGOUT_FAIL';
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';

export const LOAD_SV_START = 'LOAD_SV_START';
export const LOAD_SV_FAIL = 'LOAD_SV_FAIL';
export const LOADED_SV_SUMMARY = 'LOADED_SV_SUMMARY';
export const LOAD_SV_SUCCESS = 'LOAD_SV_SUCCESS';
export const LOAD_SV_CANCEL = 'LOAD_SV_CANCEL';

export const SET_MODULE = 'SET_MODULE';

export const LOCATOR_SEARCH ='LOCATOR_SEARCH';
export const LOCATOR_SEARCH_SUCCESS ='LOCATOR_SEARCH_SUCCESS';
export const LOCATOR_SEARCH_FAIL ='LOCATOR_SEARCH_FAIL';